// Code generated by MockGen. DO NOT EDIT.
// Source: action_service.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CountActionsByUserID mocks base method.
func (m *MockService) CountActionsByUserID(userID int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActionsByUserID", userID)
	ret0, _ := ret[0].(int)
	return ret0
}

// CountActionsByUserID indicates an expected call of CountActionsByUserID.
func (mr *MockServiceMockRecorder) CountActionsByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActionsByUserID", reflect.TypeOf((*MockService)(nil).CountActionsByUserID), userID)
}
